# Start from ROS base image
FROM osrf/ros:noetic-desktop-full-focal

# Set the working directory
WORKDIR /

# Make a catkin workspace
RUN mkdir -p /catkin_ws/src

# Change the default shell to Bash
SHELL ["/bin/bash", "-c"]

# Install necessary dependencies
RUN apt-get update && apt-get install -y 

# Copy packages of tortoisebot
COPY ./tortoisebot/tortoisebot_description /catkin_ws/src/tortoisebot_description
COPY ./tortoisebot/tortoisebot_gazebo /catkin_ws/src/tortoisebot_gazebo

# Build the Catkin workspace
RUN source /opt/ros/noetic/setup.bash \
    && cd /catkin_ws \
    && catkin_make

# Config workspace
RUN echo "source /catkin_ws/devel/setup.bash" >> ~/.bashrc

# Set the entry point to start the ROS launch file
ENTRYPOINT ["/bin/bash", "-c", "source /catkin_ws/devel/setup.bash && roslaunch tortoisebot_gazebo tortoisebot_playground.launch"]